In [ ]:
# Bibliotecas Usadas
from sys import displayhook as display
from matplotlib import pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import LabelBinarizer
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score,cohen_kappa_score , confusion_matrix , roc_auc_score
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# Lendo o data frame
df = pd.read_csv('/content/drive/MyDrive/IA-Relatorio/phishing.csv', sep=',')

In [ ]:
# Realizando a visualização as informações
display(df)

In [ ]:
# Excluindo a coluna index
df = df.drop(columns=['Index'])
display(df)

In [ ]:
# Analinisando o tipo de dados presente no data frame
display(df.info())

In [ ]:
# Trocando os valores que estão  em -1 para 0
df = df.replace(-1, 0)

In [ ]:
# Seperando as características
x = df.values[:,0:30]
y = df.values[:,30]

In [ ]:
# Normalizando o array das caracteristicas
scaler = MinMaxScaler()
x = df.values[:,0:30]
x = scaler.fit_transform(x)
print(x)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 0. 1. ... 1. 0. 0.]
 [1. 0. 1. ... 1. 0. 1.]
 ...
 [1. 0. 1. ... 1. 0. 1.]
 [0. 0. 1. ... 1. 1. 1.]
 [0. 0. 1. ... 0. 1. 0.]]


In [ ]:
# Realizando a separação teste e treino
# Sendo 80% para treino e 20% para teste
x_treino, x_teste, y_treino, y_teste = train_test_split(x,y,test_size=0.20)

In [ ]:
# Rede Neural
model = Sequential()
model.add(Dense(10,activation='relu',kernel_initializer='he_normal',input_shape=(30,)))
model.add(Dense(15,activation='relu'))
model.add(Dense(15,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

# compilacao do modelo
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
history = model.fit(x_treino,y_treino,validation_data=(x_teste,y_teste), epochs=50,batch_size=32,verbose=1)

In [ ]:
# plt.title=('Grafico de custo') # Erros
plt.subplot(211)
plt.plot(history.history['loss'], label='Perdas durante o Treinamento')
plt.plot(history.history['val_loss'], label='Perdas durante os Testes')
plt.xlabel('Epocas')
plt.ylabel('Perdas')
plt.legend()
plt.show()

In [ ]:
# plt.title('Grafico de Desempenho') # Erros
plt.plot(history.history['val_accuracy'], label='Acurácia durante os Testes')
plt.xlabel('Epocas')
plt.ylabel('Acurácia')
plt.legend()
plt.show()

In [ ]:
# Enquadrando as respostas gerada pelo modelo
previ = (model.predict(x_teste) > 0.5).astype(np.float32)
display(previ)

In [ ]:
# Gerando a matrix de confusão
matrix = confusion_matrix(y_teste,previ)
display(matrix)

In [ ]:
# Plotando a matriz de confusão
plt.imshow(matrix, interpolation='nearest', cmap=plt.cm.Blues)
plt.colorbar()

# Adicionando os valores da matriz
for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
        plt.text(j, i, format(matrix[i, j], 'd'), horizontalalignment="center", color="Black")

plt.xticks(np.arange(2), ['Falso Positivo', 'Falso Negativo'], rotation=0)
plt.yticks(np.arange(2), ['Verdadeiro Positivo', 'Verdadeiro Negativo'])
plt.xlabel('Predito')
plt.ylabel('Real')
plt.show()

In [1]:
# accuracy: (tp + tn) / (p + n)
accuracy = accuracy_score(y_teste, previ)
print('Accuracy: %f' % accuracy)

NameError: name 'accuracy_score' is not defined

In [ ]:
# precision tp / (tp + fp)
precision = precision_score(y_teste, previ)
print('Precision: %f' % precision)

Precision: 0.952911


In [ ]:
# recall: tp / (tp + fn)
recall = recall_score(y_teste, previ)
print('Recall: %f' % recall)

Recall: 0.921358


In [ ]:
# f1: 2 tp / (2 tp + fp + fn)
f1 = f1_score(y_teste, previ)
print('F1 score: %f' % f1)

F1 score: 0.936869


In [ ]:
# kappa
kappa = cohen_kappa_score(y_teste, previ)
print('Cohens kappa: %f' % kappa)

Cohens kappa: 0.863600


In [ ]:
# ROC AUC
auc = roc_auc_score(y_teste, previ)
print('ROC AUC: %f' % auc)

ROC AUC: 0.933261
